/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import com.pasien;
import com.ConvertpasienToObject;
import com.perawat;
import com.ConvertperawatToObject;
import com.ruangan;
import com.ConvertruanganToObject;
import com.pasien;
import com.ConvertpasienToObject;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class MainFormAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainFormAdmin
     */
    public MainFormAdmin() {
        initComponents();
        setdatapasien();
        setdataperawat();
        setdataruangan();
    }
    
    private void setdatapasien(){
    ConvertpasienToObject cpto = new ConvertpasienToObject();
        String[][]datapasien = cpto.getpasien();
        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
                    datapasien, new String[]{
                        "Id", "nama", "alamat","usia","jeniskelamin"
                    }
                ));
     }
    
    private void setdataperawat(){
    ConvertperawatToObject cprto = new ConvertperawatToObject();
        String[][]dataperawat = cprto.getperawat();
        tblperawat.setModel(new javax.swing.table.DefaultTableModel(
                    dataperawat, new String[]{
                        "Id", "nama", "alamat","jeniskelamin","jabatan"
                    }
                ));
    }
    
    private void setdataruangan(){
    ConvertruanganToObject crto = new ConvertruanganToObject();
        String[][]dataruangan = crto.getruangan();
        tblruangan.setModel(new javax.swing.table.DefaultTableModel(
                    dataruangan, new String[]{
                        "Id", "jenisruangan", "harga"
                    }
                ));
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnpasien = new javax.swing.JButton();
        btnperawat = new javax.swing.JButton();
        btnruangan = new javax.swing.JButton();
        pnlutama = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlpasien = new javax.swing.JPanel();
        pnlinput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpasien = new javax.swing.JTextField();
        txtalamatpasien = new javax.swing.JTextField();
        txtusiapasien = new javax.swing.JTextField();
        txtjeniskelaminpasien = new javax.swing.JTextField();
        txtnamapasien = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnubah = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        pnloutput = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpasien = new javax.swing.JTable();
        pnlperawat = new javax.swing.JPanel();
        pnlinputperawat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtidperawat = new javax.swing.JTextField();
        txtnamaperawat = new javax.swing.JTextField();
        txtalamatperawat = new javax.swing.JTextField();
        txtjeniskelaminperawat = new javax.swing.JTextField();
        txtjabatanperawat = new javax.swing.JTextField();
        btnsimpanperawat = new javax.swing.JButton();
        btnubatperawat = new javax.swing.JButton();
        btnhapusperawat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblperawat = new javax.swing.JTable();
        pnlruangan = new javax.swing.JPanel();
        pnlinputruangan = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtidruangan = new javax.swing.JTextField();
        txtjenisruangan = new javax.swing.JTextField();
        txthargaruangan = new javax.swing.JTextField();
        btnsimpanruangan = new javax.swing.JButton();
        btnubahruangan = new javax.swing.JButton();
        btndeleteruangan = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblruangan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnpasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pasien1.png"))); // NOI18N
        btnpasien.setText("Pasien");
        btnpasien.setFocusable(false);
        btnpasien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpasien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpasienActionPerformed(evt);
            }
        });
        jToolBar1.add(btnpasien);

        btnperawat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/perawat1.png"))); // NOI18N
        btnperawat.setText("Perawat");
        btnperawat.setFocusable(false);
        btnperawat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnperawat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnperawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnperawatActionPerformed(evt);
            }
        });
        jToolBar1.add(btnperawat);

        btnruangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/ruangan1.png"))); // NOI18N
        btnruangan.setText("Ruangan");
        btnruangan.setFocusable(false);
        btnruangan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnruangan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnruanganActionPerformed(evt);
            }
        });
        jToolBar1.add(btnruangan);

        pnlutama.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel1.setText("Panel Admin");
        pnlutama.add(jLabel1, "card2");

        jLabel2.setText("ID Pasien");

        jLabel3.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel5.setText("Usia");

        jLabel6.setText("Jenis Kelamin");

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnubah.setText("Ubah");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });

        jLabel22.setText("Pasien");

        javax.swing.GroupLayout pnlinputLayout = new javax.swing.GroupLayout(pnlinput);
        pnlinput.setLayout(pnlinputLayout);
        pnlinputLayout.setHorizontalGroup(
            pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputLayout.createSequentialGroup()
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlinputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(75, 75, 75)
                        .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpasien, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(txtnamapasien)
                            .addComponent(txtalamatpasien)
                            .addComponent(txtusiapasien)
                            .addComponent(txtjeniskelaminpasien)))
                    .addGroup(pnlinputLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnsimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnubah, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlinputLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel22)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnlinputLayout.setVerticalGroup(
            pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(37, 37, 37)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamapasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtalamatpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtusiapasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjeniskelaminpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(pnlinputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan)
                    .addComponent(btnubah)
                    .addComponent(btnhapus))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        tblpasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpasienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpasien);

        javax.swing.GroupLayout pnloutputLayout = new javax.swing.GroupLayout(pnloutput);
        pnloutput.setLayout(pnloutputLayout);
        pnloutputLayout.setHorizontalGroup(
            pnloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloutputLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnloutputLayout.setVerticalGroup(
            pnloutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnloutputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlpasienLayout = new javax.swing.GroupLayout(pnlpasien);
        pnlpasien.setLayout(pnlpasienLayout);
        pnlpasienLayout.setHorizontalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnloutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlpasienLayout.setVerticalGroup(
            pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlpasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlinput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnloutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlutama.add(pnlpasien, "cardpasien");

        jLabel7.setText("ID Perawat");

        jLabel8.setText("Nama");

        jLabel9.setText("Alamat");

        jLabel10.setText("Jenis Kelamin");

        jLabel11.setText("Jabatan");

        jLabel12.setText("Perawat");

        btnsimpanperawat.setText("Simpan");
        btnsimpanperawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanperawatActionPerformed(evt);
            }
        });

        btnubatperawat.setText("Ubah");
        btnubatperawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubatperawatActionPerformed(evt);
            }
        });

        btnhapusperawat.setText("Hapus");
        btnhapusperawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusperawatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlinputperawatLayout = new javax.swing.GroupLayout(pnlinputperawat);
        pnlinputperawat.setLayout(pnlinputperawatLayout);
        pnlinputperawatLayout.setHorizontalGroup(
            pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputperawatLayout.createSequentialGroup()
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlinputperawatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(84, 84, 84)
                        .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidperawat, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(txtnamaperawat)
                            .addComponent(txtalamatperawat)
                            .addComponent(txtjeniskelaminperawat)
                            .addComponent(txtjabatanperawat)))
                    .addGroup(pnlinputperawatLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnsimpanperawat)
                        .addGap(18, 18, 18)
                        .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(pnlinputperawatLayout.createSequentialGroup()
                                .addComponent(btnubatperawat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnhapusperawat, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnlinputperawatLayout.setVerticalGroup(
            pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputperawatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(44, 44, 44)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtidperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtnamaperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtalamatperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtjeniskelaminperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtjabatanperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpanperawat)
                    .addComponent(btnubatperawat)
                    .addComponent(btnhapusperawat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblperawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblperawat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblperawatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblperawat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlperawatLayout = new javax.swing.GroupLayout(pnlperawat);
        pnlperawat.setLayout(pnlperawatLayout);
        pnlperawatLayout.setHorizontalGroup(
            pnlperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlperawatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlinputperawat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlperawatLayout.setVerticalGroup(
            pnlperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlperawatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlperawatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlinputperawat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlutama.add(pnlperawat, "cardperawat");

        jLabel13.setText("ID Ruangan");

        jLabel14.setText("Jenis Ruangan");

        jLabel15.setText("Harga");

        btnsimpanruangan.setText("Simpan");
        btnsimpanruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanruanganActionPerformed(evt);
            }
        });

        btnubahruangan.setText("Ubah");
        btnubahruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahruanganActionPerformed(evt);
            }
        });

        btndeleteruangan.setText("Delete");
        btndeleteruangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteruanganActionPerformed(evt);
            }
        });

        jLabel23.setText("Ruangan");

        javax.swing.GroupLayout pnlinputruanganLayout = new javax.swing.GroupLayout(pnlinputruangan);
        pnlinputruangan.setLayout(pnlinputruanganLayout);
        pnlinputruanganLayout.setHorizontalGroup(
            pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputruanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlinputruanganLayout.createSequentialGroup()
                        .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(89, 89, 89)
                        .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidruangan, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtjenisruangan)
                            .addComponent(txthargaruangan)))
                    .addGroup(pnlinputruanganLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnsimpanruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(pnlinputruanganLayout.createSequentialGroup()
                                .addComponent(btnubahruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btndeleteruangan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        pnlinputruanganLayout.setVerticalGroup(
            pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlinputruanganLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel23)
                .addGap(57, 57, 57)
                .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtidruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtjenisruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txthargaruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(pnlinputruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeleteruangan)
                    .addComponent(btnsimpanruangan)
                    .addComponent(btnubahruangan))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        tblruangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblruangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblruanganMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblruangan);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );

        javax.swing.GroupLayout pnlruanganLayout = new javax.swing.GroupLayout(pnlruangan);
        pnlruangan.setLayout(pnlruanganLayout);
        pnlruanganLayout.setHorizontalGroup(
            pnlruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlruanganLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlinputruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlruanganLayout.setVerticalGroup(
            pnlruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlruanganLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlruanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlinputruangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlutama.add(pnlruangan, "cardruangan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpasienActionPerformed
       cl = (CardLayout) pnlutama.getLayout();
        cl.show(pnlutama, "cardpasien");
    }//GEN-LAST:event_btnpasienActionPerformed

    private void tblpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpasienMouseClicked
        int row = tblpasien.getSelectedRow();
        String id_pasien = tblpasien.getValueAt(row, 0).toString();
        String nama = tblpasien.getValueAt(row, 1).toString();
        String alamat = tblpasien.getValueAt(row, 2).toString();
        String usia = tblpasien.getValueAt(row, 3).toString();
	String jeniskelamin = tblpasien.getValueAt(row, 3).toString();
        txtpasien.setText(id_pasien);
        txtnamapasien.setText(nama);
        txtalamatpasien.setText(alamat);
        txtusiapasien.setText(usia);
	txtjeniskelaminpasien.setText(jeniskelamin);
    }//GEN-LAST:event_tblpasienMouseClicked

    private void btnperawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnperawatActionPerformed
        cl = (CardLayout) pnlutama.getLayout();
        cl.show(pnlutama, "cardperawat");
    }//GEN-LAST:event_btnperawatActionPerformed

    private void btnruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnruanganActionPerformed
        cl = (CardLayout) pnlutama.getLayout();
        cl.show(pnlutama, "cardruangan");
    }//GEN-LAST:event_btnruanganActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        String strid_pasien = txtpasien.getText();
        int id_pasien = Integer.parseInt(strid_pasien);
        String nama = txtnamapasien.getText();
        String alamat = txtalamatpasien.getText();
        String strusia = txtusiapasien.getText();
        int usia = Integer.parseInt(strusia);
        String jeniskelamin = txtjeniskelaminpasien.getText();
        
        pasien psn = new pasien(id_pasien, nama, alamat, usia, jeniskelamin);
        exec.executepasien epsn = new exec.executepasien();
        int hasil = epsn.insertData(psn);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdatapasien();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        String strid_pasien = txtpasien.getText();
        int id_pasien = Integer.parseInt(strid_pasien);
        String nama = txtnamapasien.getText();
        String alamat = txtalamatpasien.getText();
        String strusia = txtusiapasien.getText();
        int usia = Integer.parseInt(strusia);
        String jeniskelamin = txtjeniskelaminpasien.getText();
        
        pasien psn = new pasien(id_pasien, nama, alamat, usia, jeniskelamin);
        exec.executepasien epsn = new exec.executepasien();
        int hasil = epsn.ubahData(psn);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdatapasien();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        String strid_pasien = txtpasien.getText();
        int id_pasien = Integer.parseInt(strid_pasien);
        
        exec.executepasien epsn = new exec.executepasien();
        int hasil = epsn.hapusData(id_pasien);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setdatapasien();
        }
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanperawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanperawatActionPerformed
        String strid_perawat = txtidperawat.getText();
        int id_perawat = Integer.parseInt(strid_perawat);
        String nama = txtnamaperawat.getText();
        String alamat = txtalamatperawat.getText();
        String jeniskelamin = txtjeniskelaminperawat.getText();
        String jabatan = txtjabatanperawat.getText();
        
        perawat prw = new perawat(id_perawat, nama, alamat, jeniskelamin, jabatan);
        exec.executeperawat eprw = new exec.executeperawat();
        int hasil = eprw.insertData(prw);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataperawat();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnsimpanperawatActionPerformed

    private void btnubatperawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubatperawatActionPerformed
        String strid_perawat = txtidperawat.getText();
        int id_perawat = Integer.parseInt(strid_perawat);
        String nama = txtnamaperawat.getText();
        String alamat = txtalamatperawat.getText();
        String jeniskelamin = txtjeniskelaminperawat.getText();
        String jabatan = txtjabatanperawat.getText();
        
        perawat prw = new perawat(id_perawat, nama, alamat, jeniskelamin, jabatan);
        exec.executeperawat eprw = new exec.executeperawat();
        int hasil = eprw.ubahData(prw);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataperawat();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnubatperawatActionPerformed

    private void btnhapusperawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusperawatActionPerformed
        String strid_perawat = txtidperawat.getText();
        int id_perawat = Integer.parseInt(strid_perawat);
        
        exec.executeperawat eprw = new exec.executeperawat();
        int hasil = eprw.hapusData(id_perawat);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setdataperawat();
        }
    }//GEN-LAST:event_btnhapusperawatActionPerformed

    private void tblperawatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblperawatMouseClicked
        int row = tblperawat.getSelectedRow();
        String id_perawat = tblperawat.getValueAt(row, 0).toString();
        String nama = tblperawat.getValueAt(row, 1).toString();
        String alamat = tblperawat.getValueAt(row, 2).toString();
        String jeniskelamin = tblperawat.getValueAt(row, 3).toString();
	String jabatan= tblperawat.getValueAt(row, 4).toString();
        txtidperawat.setText(id_perawat);
        txtnamaperawat.setText(nama);
        txtalamatperawat.setText(alamat);
        txtjeniskelaminperawat.setText(jeniskelamin);
	txtjabatanperawat.setText(jabatan);
    }//GEN-LAST:event_tblperawatMouseClicked

    private void btnsimpanruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanruanganActionPerformed
        String strid_ruangan = txtidruangan.getText();
        int id_ruangan = Integer.parseInt(strid_ruangan);
        String jenis_ruangan = txtjenisruangan.getText();
        String strharga = txthargaruangan.getText();
        int harga = Integer.parseInt(strharga);

        
        ruangan rgn = new ruangan(id_ruangan, jenis_ruangan, harga);
        exec.executeruangan ergn = new exec.executeruangan();
        int hasil = ergn.insertData(rgn);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataruangan();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnsimpanruanganActionPerformed

    private void btnubahruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahruanganActionPerformed
        String strid_ruangan = txtidruangan.getText();
        int id_ruangan = Integer.parseInt(strid_ruangan);
        String jenisruangan = txtjenisruangan.getText();
        String strharga = txthargaruangan.getText();
        int harga = Integer.parseInt(strharga);
        ruangan rgn = new ruangan(id_ruangan, jenisruangan, harga);
        exec.executeruangan ergn = new exec.executeruangan();
        int hasil = ergn.ubahData(rgn);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            setdataruangan();
           
        }
        else {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan");
        }
    }//GEN-LAST:event_btnubahruanganActionPerformed

    private void btndeleteruanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteruanganActionPerformed
        String strid_ruangan = txtidruangan.getText();
        int id_ruangan = Integer.parseInt(strid_ruangan);
        
        exec.executeruangan ergn = new exec.executeruangan();
        int hasil = ergn.hapusData(id_ruangan);
        if(hasil >0){
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
            setdataruangan();
        }
    }//GEN-LAST:event_btndeleteruanganActionPerformed

    private void tblruanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblruanganMouseClicked
        int row = tblruangan.getSelectedRow();
        String id_ruangan = tblruangan.getValueAt(row, 0).toString();
        String jenisruangan = tblruangan.getValueAt(row, 1).toString();
        String harga = tblruangan.getValueAt(row, 2).toString();
        txtidruangan.setText(id_ruangan);
        txtjenisruangan.setText(jenisruangan);
        txthargaruangan.setText(harga);

    }//GEN-LAST:event_tblruanganMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFormAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFormAdmin().setVisible(true);
            }
        });
    }
    private CardLayout cl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndeleteruangan;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapusperawat;
    private javax.swing.JButton btnpasien;
    private javax.swing.JButton btnperawat;
    private javax.swing.JButton btnruangan;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnsimpanperawat;
    private javax.swing.JButton btnsimpanruangan;
    private javax.swing.JButton btnubah;
    private javax.swing.JButton btnubahruangan;
    private javax.swing.JButton btnubatperawat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnlinput;
    private javax.swing.JPanel pnlinputperawat;
    private javax.swing.JPanel pnlinputruangan;
    private javax.swing.JPanel pnloutput;
    private javax.swing.JPanel pnlpasien;
    private javax.swing.JPanel pnlperawat;
    private javax.swing.JPanel pnlruangan;
    private javax.swing.JPanel pnlutama;
    private javax.swing.JTable tblpasien;
    private javax.swing.JTable tblperawat;
    private javax.swing.JTable tblruangan;
    private javax.swing.JTextField txtalamatpasien;
    private javax.swing.JTextField txtalamatperawat;
    private javax.swing.JTextField txthargaruangan;
    private javax.swing.JTextField txtidperawat;
    private javax.swing.JTextField txtidruangan;
    private javax.swing.JTextField txtjabatanperawat;
    private javax.swing.JTextField txtjeniskelaminpasien;
    private javax.swing.JTextField txtjeniskelaminperawat;
    private javax.swing.JTextField txtjenisruangan;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JTextField txtnamaperawat;
    private javax.swing.JTextField txtpasien;
    private javax.swing.JTextField txtusiapasien;
    // End of variables declaration//GEN-END:variables
}
